name = "oce server"
author = "henkelmax (hermitcraft-server) & JustPyrrha (oce server)"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ef38bbd8891476ff07a0ab04e46d5eb665be8dc053294b7875b5221bb93bbf99"

[versions]
fabric = "0.18.4"
minecraft = "26.1"
unsup = "1.1.6"

[options]
acceptable-game-versions = []
datapack-folder = "datapacks"
