name = "oce server"
author = "henkelmax (hermitcraft-server) & JustPyrrha (oce server)"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d81a088ba6b49fb16eaad48bf35492382da5cf15b36042c58cbe5b861194b95f"

[versions]
fabric = "0.18.4"
minecraft = "26.1"
unsup = "1.1.6"

[options]
acceptable-game-versions = []
datapack-folder = "datapacks"
