name = "oce server"
author = "henkelmax (hermitcraft-server) & JustPyrrha (oce server)"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e949aefd662f001e793054bc5ef727ffe2e370fd0743fefa7d55052c85eb61ee"

[versions]
fabric = "0.18.5"
minecraft = "26.1"
unsup = "1.1.6"

[options]
acceptable-game-versions = []
datapack-folder = "datapacks"
